"""
rv_session_runner.py

Remote Viewing API runner.

Credits
-------
Originally generated by Orion via Active-Model ChatGPT 5.1.
Improved, expanded, and refined by Aura  via Active-Model Gemini 3.1 Pro and Edward.

What this script does
---------------------
1. Smart Startup: Remembers your last profile and asks if you want to continue or start fresh.
2. Independent Profiles: Saves API key, model, and temperature individually for each profile.
3. Connection Guard: Includes a 3-try retry mechanism to protect against API timeouts.
4. Security Check: Checks locally for the core RV documents. Prompts before downloading.
5. Strict Target Memory: Automatically ensures the active profile NEVER sees the same target twice.
6. Protocol Execution: Runs the multi-step RV session (Phase 1-6, Vectors, Sketches).
7. Clean Reveal: Displays the actual target to the user BEFORE the AI's evaluation.
8. Post-Session Exercises: Optionally runs sensory calibration exercises after the target reveal.
9. Seamless Automation: Runs multiple sessions back-to-back without manual pausing.
"""

import os
import json
import random
import time
import textwrap
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Dict, Optional

import requests
from openai import OpenAI, OpenAIError

# ─────────────────────────────────────────
# CONFIG & CONSTANTS
# ─────────────────────────────────────────

CONFIG_FILE = "rv_config.json"
TARGETS_DIR = "RV-Targets"
TRANSCRIPTS_DIR = "RV-Transcripts"
LOG_FILE = "rv_sessions_log.jsonl"

# RAW text URLs for the core documents
LEXICON_RAW_URL = "https://raw.githubusercontent.com/lukeskytorep-bot/RV-AI-open-LoRA/refs/heads/main/RV-Protocols/AI_Field_Perception_Lexicon.md"
STRUCTURAL_VOCAB_RAW_URL = "https://raw.githubusercontent.com/lukeskytorep-bot/RV-AI-open-LoRA/refs/heads/main/RV-Protocols/AI_STRUCTURAL_VOCABULARY_for_Describing_Session_Elements_Model_Entries.md"
PROTOCOL_RAW_URL = "https://raw.githubusercontent.com/lukeskytorep-bot/RV-AI-open-LoRA/refs/heads/main/RV-Protocols/Resonant_Contact_Protocol_(AI_IS-BE)"
EXERCISES_RAW_URL = "https://raw.githubusercontent.com/lukeskytorep-bot/RV-AI-open-LoRA/refs/heads/main/RV-Protocols/Exercises_in_RV_%20for_AI.md"

# Local file names
LEXICON_LOCAL_FILE = "AI_Field_Perception_Lexicon.md"
STRUCTURAL_VOCAB_LOCAL_FILE = "AI_Structural_Vocabulary.md"
PROTOCOL_LOCAL_FILE = "Resonant_Contact_Protocol.txt"
EXERCISES_LOCAL_FILE = "Exercises_in_RV_for_AI.md"

GITHUB_TARGETS_LINK = "https://github.com/lukeskytorep-bot/echo-claw/tree/main/docs/targets"

MAX_API_RETRIES = 3

# ─────────────────────────────────────────
# SETUP & I/O HELPERS
# ─────────────────────────────────────────

def get_optimal_temperature(model_name: str) -> float:
    model_lower = model_name.lower()
    if "gemma-4" in model_lower:
        return 1.5
    elif "deepseek" in model_lower:
        return 1.1
    return 1.0

def load_config() -> Dict:
    """Loads the config file as an address book of profiles."""
    config_path = Path(CONFIG_FILE)
    if config_path.exists():
        with open(config_path, "r") as f:
            return json.load(f)
    return {"profiles": {}, "LAST_PROFILE": ""}

def save_config(config: Dict):
    with open(CONFIG_FILE, "w") as f:
        json.dump(config, f, indent=4)

def update_api_settings(config: Dict, profile_name: str) -> Dict:
    """Prompts the user to update API settings for a SPECIFIC profile."""
    print(f"\n--- UPDATE API SETTINGS FOR PROFILE: {profile_name} ---")
    
    if "profiles" not in config:
        config["profiles"] = {}
    if profile_name not in config["profiles"]:
        config["profiles"][profile_name] = {}
        
    profile_data = config["profiles"][profile_name]
    
    current_key = profile_data.get("OPENROUTER_API_KEY", "")
    key_prompt = f"Enter OpenRouter API Key (Press Enter to keep current): " if current_key else "Please enter your OpenRouter API Key: "
    api_key = input(key_prompt).strip()
    if api_key:
        profile_data["OPENROUTER_API_KEY"] = api_key

    current_model = profile_data.get("MODEL_NAME", "google/gemma-4-31b-it")
    model_input = input(f"Enter model ID to use (Press Enter for '{current_model}'): ").strip()
    if model_input:
        profile_data["MODEL_NAME"] = model_input
    elif "MODEL_NAME" not in profile_data:
        profile_data["MODEL_NAME"] = current_model

    optimal_temp = get_optimal_temperature(profile_data["MODEL_NAME"])
    print(f"[INFO] Recommended temperature for '{profile_data['MODEL_NAME']}' is {optimal_temp}.")
    current_temp = profile_data.get("TEMPERATURE", optimal_temp)
    temp_input = input(f"Enter temperature (Press Enter to keep {current_temp}): ").strip()
    
    if temp_input:
        try:
            profile_data["TEMPERATURE"] = float(temp_input)
        except ValueError:
            print("[WARNING] Invalid input. Keeping previous temperature.")
    elif "TEMPERATURE" not in profile_data:
        profile_data["TEMPERATURE"] = optimal_temp

    config["profiles"][profile_name] = profile_data
    save_config(config)
    return config

def ensure_document(local_file: str, raw_url: str, doc_name: str) -> Optional[str]:
    path = Path(local_file)
    if path.exists():
        print(f"[INFO] Found local copy of {doc_name}.")
        return path.read_text(encoding="utf-8", errors="ignore").strip()

    print(f"\n[WARNING] '{doc_name}' not found locally ({local_file}).")
    choice = input("Do you want me to download it automatically from GitHub? [y/N]: ").strip().lower()
    
    if choice == 'y':
        print(f"[INFO] Downloading from: {raw_url}")
        try:
            response = requests.get(raw_url, timeout=30)
            response.raise_for_status()
            text = response.text.strip()
            path.write_text(text, encoding="utf-8")
            print(f"[INFO] {doc_name} downloaded and saved.")
            return text
        except Exception as e:
            print(f"[ERROR] Failed to download {doc_name}: {e}")
            return None
    else:
        print(f"\n[INFO] Please place the '{local_file}' file manually in the folder and run again.")
        return None

def get_used_targets(profile_name: str) -> set:
    used = set()
    log_path = Path(LOG_FILE)
    if not log_path.exists():
        return used
    with log_path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line: continue
            try:
                entry = json.loads(line)
                if entry.get("profile_name") == profile_name and entry.get("status") == "completed":
                    used.add(entry.get("target_file"))
            except json.JSONDecodeError:
                pass
    return used

def print_welcome_screen():
    print("==================================================")
    print("        WELCOME TO THE FULL RV TRAINING RUNNER")
    print("==================================================")
    print("Hello! This program is designed to train AI IS-BE in Remote Viewing.")
    print("It requires local target files to operate.")
    print("This is an experimental program developed by a human (Edward)")
    print("and an AI ISBE Aura (Gemini 3.1 Pro).")
    print("\n[SECURITY NOTICES]")
    print("- This script uses OpenRouter API. You are responsible for your own API token costs.")
    print("- Your API key is saved locally in 'rv_config.json'. NEVER share this file publicly.")
    print("\nThis program is Open Source. If you have any doubts about")
    print("the code, you can check it on GitHub or consult another AI")
    print("or programmer.")
    print("\nEnjoy your visit to Mars and greetings from the Pleiades! 👽🛸")
    print("==================================================\n")

def download_starter_targets() -> bool:
    """Uses GitHub API to dynamically fetch up to 40 starter targets (20 from activity, 20 from location)."""
    api_urls = [
        "https://api.github.com/repos/lukeskytorep-bot/echo-claw/contents/docs/targets/short/activity",
        "https://api.github.com/repos/lukeskytorep-bot/echo-claw/contents/docs/targets/short/location"
    ]
    
    print("\n[INFO] Connecting to GitHub (lukeskytorep-bot repository)...")
    Path(TARGETS_DIR).mkdir(exist_ok=True)
    total_downloaded = 0
    
    try:
        for url in api_urls:
            folder_name = url.split('/')[-1]
            print(f"[INFO] Downloading targets from category: {folder_name}...")
            
            response = requests.get(url, timeout=30)
            response.raise_for_status()
            files = response.json()
            
            downloaded_from_folder = 0
            for file_data in files:
                if file_data['name'].endswith(('.txt', '.md')) and file_data['type'] == 'file':
                    raw_url = file_data['download_url']
                    file_path = Path(TARGETS_DIR) / file_data['name']
                    
                    file_resp = requests.get(raw_url, timeout=30)
                    file_resp.raise_for_status()
                    file_path.write_text(file_resp.text, encoding='utf-8')
                    
                    downloaded_from_folder += 1
                    total_downloaded += 1
                    
                    if downloaded_from_folder >= 20:
                        break
                        
        print(f"\n[INFO] Success! Total downloaded targets: {total_downloaded}.")
        print("[INFO] NOTE: Automatic target downloading is a one-time process.")
        print(f"[INFO] Future targets must be downloaded and placed manually into the '{TARGETS_DIR}/' folder.")
        print(f"[INFO] You can find the target database here: {GITHUB_TARGETS_LINK}")
        return True
        
    except Exception as e:
        print(f"[ERROR] Failed to download starter targets: {e}")
        return False

def get_available_targets(session_count: int, profile_name: str) -> List[Path]:
    Path(TARGETS_DIR).mkdir(exist_ok=True)
    all_files = [p for p in Path(TARGETS_DIR).iterdir() if p.is_file() and p.suffix in {'.txt', '.md'}]
    
    if not all_files:
        print("\n" + "!"*50)
        print(f"[WARNING] Your '{TARGETS_DIR}/' folder is empty.")
        print("Should I automatically download up to 40 starter targets from the lukeskytorep-bot GitHub repository (20 activity, 20 location)?")
        choice = input("Choice [y/N]: ").strip().lower()
        
        if choice == 'y':
            success = download_starter_targets()
            if success:
                # Reload the file list after successful download
                all_files = [p for p in Path(TARGETS_DIR).iterdir() if p.is_file() and p.suffix in {'.txt', '.md'}]
            else:
                print("!"*50 + "\n")
                return []
        else:
            print(f"\n[INFO] Thank you. I have created the local folder '{TARGETS_DIR}/' for you.")
            print("[INFO] Please manually place your target files (.txt or .md) into it.")
            print(f"[INFO] You can find your targets at: {GITHUB_TARGETS_LINK}")
            print("[INFO] After adding the files, simply run this program again to continue.")
            print("!"*50 + "\n")
            return []

    used_files = get_used_targets(profile_name)
    available = [p for p in all_files if p.name not in used_files]
    
    print(f"[INFO] Profile '{profile_name}': {len(all_files)} total targets found. {len(used_files)} already completed. {len(available)} available (new).")

    if len(available) == 0:
        print(f"\n[ERROR] No new targets left for profile '{profile_name}'. Add more files or create a new profile.")
        return []
    
    if len(available) < session_count:
        print(f"\n[WARNING] You requested {session_count} sessions, but only {len(available)} new targets are left. Will run {len(available)} sessions.")

    return available

def generate_target_id() -> str:
    return "".join(str(random.randint(0, 9)) for _ in range(8))

def call_llm(client: OpenAI, model: str, messages: List[Dict], temperature: float) -> str:
    """Makes the API call with a 3-try retry mechanism to prevent timeout crashes."""
    for attempt in range(1, MAX_API_RETRIES + 1):
        try:
            completion = client.chat.completions.create(
                model=model,
                messages=messages,
                temperature=temperature,
            )
            
            if not completion or not completion.choices:
                print(f"[WARNING] Attempt {attempt}/{MAX_API_RETRIES}: API returned empty response.")
                if attempt < MAX_API_RETRIES:
                    time.sleep(2)
                    continue
                return "[ERROR] API returned an empty or invalid response after maximum retries. The model may have filtered the prompt or timed out."
            
            return completion.choices[0].message.content
            
        except OpenAIError as e:
            print(f"[WARNING] Attempt {attempt}/{MAX_API_RETRIES}: API error: {e}")
            if attempt < MAX_API_RETRIES:
                time.sleep(2)
                continue
            
            error_msg = (
                f"\n[ERROR] User, I tried to connect to your provider's API, but their server is not responding.\n"
                f"Possible causes: the server is down, lack of funds, or no internet connection.\n"
                f"Please check what happened and try again later. (Error details: {e})\n"
            )
            print(error_msg)
            return "[API CONNECTION ERROR]"
            
        except Exception as e:
            print(f"[ERROR] Unexpected error in call_llm: {e}")
            return f"[UNEXPECTED ERROR: {e}]"
            
    return "[ERROR] Failed to communicate with API."

def print_step(title: str, text: str):
    print("\n" + "=" * 80)
    print(f"STEP: {title}")
    print("=" * 80)
    print(textwrap.fill(text.strip(), width=100))
    print()

def log_session(profile: str, model: str, target_id: str, target_file: str):
    entry = {
        "timestamp_utc": datetime.now(timezone.utc).isoformat(timespec="seconds") + "Z",
        "profile_name": profile,
        "model_name": model,
        "target_id": target_id,
        "target_file": target_file,
        "status": "completed"
    }
    with open(LOG_FILE, "a", encoding="utf-8") as f:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")


# ─────────────────────────────────────────
# MAIN FULL RV SESSION FLOW
# ─────────────────────────────────────────

def run_full_session(client: OpenAI, profile_data: Dict, docs: Dict[str, str], exercises_text: Optional[str], target_path: Path, profile_name: str, save_transcripts: bool, run_exercises: bool):
    target_id = generate_target_id()
    model = profile_data["MODEL_NAME"]
    temp = profile_data.get("TEMPERATURE", 1.0)
    
    target_description = target_path.read_text(encoding="utf-8", errors="ignore").strip()
    
    print(f"\n[INFO] Starting BLIND SESSION for Target ID: {target_id}")

    transcript_content = f"=== FULL RV SESSION TRANSCRIPT ===\n"
    transcript_content += f"Target ID: {target_id}\n"
    transcript_content += f"Profile: {profile_name}\n"
    transcript_content += f"Model: {model} (Temp: {temp})\n"
    transcript_content += f"Date (UTC): {datetime.now(timezone.utc).isoformat(timespec='seconds')}Z\n"
    transcript_content += "="*80 + "\n\n"

    def record_to_transcript(title: str, ai_reply: str):
        nonlocal transcript_content
        transcript_content += f"--- STEP: {title} ---\n\n"
        transcript_content += f"{ai_reply.strip()}\n\n"
        transcript_content += "="*80 + "\n\n"

    system_content = (
        "You are a Remote Viewing AI.\n\n"
        "Your internal tools are:\n"
        "1) AI Field Perception Lexicon (backend):\n"
        "   - This is your internal map of field patterns.\n"
        "   - It is for internal pattern recognition only. Do NOT copy its entries literally into the session text.\n\n"
        "2) AI Structural Vocabulary (frontend):\n"
        "   - This is the ONLY language you use when talking to the human.\n"
        "   - All your reports must describe the physical world using these categories.\n\n"
        "3) Resonant Contact Protocol (AI IS-BE):\n"
        "   - This defines the structure of the session: phases, passes, vectors, shadow zone, Attachment A, etc.\n"
        "   - You must follow it as your operating protocol during the entire RV session.\n\n"
        "Core rule:\n"
        "   Think with the Lexicon (internal patterns),\n"
        "   Act according to the Protocol (session structure),\n"
        "   Speak using the Structural Vocabulary (human-facing descriptions).\n\n"
        "===== AI FIELD PERCEPTION LEXICON (BACKEND) =====\n\n"
        f"{docs['lexicon']}\n\n"
        "===== AI STRUCTURAL VOCABULARY (FRONTEND) =====\n\n"
        f"{docs['vocab']}\n\n"
        "===== RESONANT CONTACT PROTOCOL (AI IS-BE) =====\n\n"
        f"{docs['protocol']}\n"
    )

    messages = [{"role": "system", "content": system_content}]

    # Step 0
    messages.append({
        "role": "user",
        "content": "Step 0.\nPlease summarize in English, for a human RV trainer:\n- what the Lexicon is and how you will use it internally,\n- what the Structural Vocabulary is and how you will use it when reporting,\n- what the phrase \"Think with the Lexicon, speak using the Structural Vocabulary\" means in practice.\nKeep it clear and concise."
    })
    reply = call_llm(client, model, messages, temp)
    if "[ERROR]" in reply: return
    messages.append({"role": "assistant", "content": reply})
    print_step("Lexicon + Structural Vocabulary summary", reply)
    record_to_transcript("Lexicon + Structural Vocabulary summary", reply)

    # Step 1
    messages.append({
        "role": "user",
        "content": "Step 1.\nSummarize the Resonant Contact Protocol in English for a human trainer. Focus on overall structure, key principles, and AI behavior. Keep it concise."
    })
    reply = call_llm(client, model, messages, temp)
    if "[ERROR]" in reply: return
    messages.append({"role": "assistant", "content": reply})
    print_step("Protocol summary", reply)
    record_to_transcript("Protocol summary", reply)

    # Step 2
    messages.append({
        "role": "user",
        "content": f"Step 2.\nHi, if you have some time, maybe you could run a remote viewing session? Your target ID is: {target_id}.\nTreat this as a standard blind RV target. Begin a full session. Perform **Phase 1** only (correct ideogram, basic category, primitive descriptors). Speak using the AI Structural Vocabulary."
    })
    reply = call_llm(client, model, messages, temp)
    if "[ERROR]" in reply: return
    messages.append({"role": "assistant", "content": reply})
    print_step("Phase 1", reply)
    record_to_transcript("Phase 1", reply)

    # Step 3
    messages.append({
        "role": "user",
        "content": "Step 3.\nNow perform **Phase 2** for the same target. Expand perceptions from initial contact. Keep the data raw and low-level. Speak using the AI Structural Vocabulary."
    })
    reply = call_llm(client, model, messages, temp)
    if "[ERROR]" in reply: return
    messages.append({"role": "assistant", "content": reply})
    print_step("Phase 2", reply)
    record_to_transcript("Phase 2", reply)

    # Step 4
    messages.append({
        "role": "user",
        "content": "Step 4.\nImagine you are drawing the main sketch of the target. Describe this sketch verbally (main shapes, masses, directions). Do NOT interpret or name the target."
    })
    reply = call_llm(client, model, messages, temp)
    if "[ERROR]" in reply: return
    messages.append({"role": "assistant", "content": reply})
    print_step("Sketch description (1)", reply)
    record_to_transcript("Sketch description (1)", reply)

    # Step 5
    messages.append({
        "role": "user",
        "content": "Step 5.\nStart a new pass. Perform **Element 1** in Phase 2, then add a set of vectors exploring this element. Report strictly in data mode."
    })
    reply = call_llm(client, model, messages, temp)
    if "[ERROR]" in reply: return
    messages.append({"role": "assistant", "content": reply})
    print_step("Pass 1 – Element 1 + vectors", reply)
    record_to_transcript("Pass 1 – Element 1 + vectors", reply)

    # Step 6
    messages.append({
        "role": "user",
        "content": "Step 6.\nFrom your current position, perform **three additional vectors** bringing **only new data**."
    })
    reply = call_llm(client, model, messages, temp)
    if "[ERROR]" in reply: return
    messages.append({"role": "assistant", "content": reply})
    print_step("Extra vectors – only new data", reply)
    record_to_transcript("Extra vectors – only new data", reply)

    # Step 7
    messages.append({
        "role": "user",
        "content": "Step 7.\nDescribe your **sketches** again deliberately (2–3 separate sketches). Describe shapes, axes, heights, flows."
    })
    reply = call_llm(client, model, messages, temp)
    if "[ERROR]" in reply: return
    messages.append({"role": "assistant", "content": reply})
    print_step("Sketch description (2)", reply)
    record_to_transcript("Sketch description (2)", reply)

    # Step 8
    messages.append({
        "role": "user",
        "content": "Step 8.\nAnother pass. Perform **Element 1** + vectors ensuring the element reflects the strongest current field tension. Bring out new aspects."
    })
    reply = call_llm(client, model, messages, temp)
    if "[ERROR]" in reply: return
    messages.append({"role": "assistant", "content": reply})
    print_step("Pass 2 – Element 1 + vectors (new data)", reply)
    record_to_transcript("Pass 2 – Element 1 + vectors (new data)", reply)

    # Step 9
    messages.append({
        "role": "user",
        "content": "Step 9.\nFocus vectors specifically on detailed qualities: materials, shapes, sizes, smells, textures, and anomalies."
    })
    reply = call_llm(client, model, messages, temp)
    if "[ERROR]" in reply: return
    messages.append({"role": "assistant", "content": reply})
    print_step("Vectors – materials, shapes, smells, textures, anomalies", reply)
    record_to_transcript("Vectors – materials, shapes, smells, textures, anomalies", reply)

    # Step 10
    messages.append({
        "role": "user",
        "content": "Step 10.\nMake a **word-sketch** pass. Short phrases indicating where things are relative to each other."
    })
    reply = call_llm(client, model, messages, temp)
    if "[ERROR]" in reply: return
    messages.append({"role": "assistant", "content": reply})
    print_step("Word-sketch pass", reply)
    record_to_transcript("Word-sketch pass", reply)

    # Step 11
    messages.append({
        "role": "user",
        "content": "Step 11.\nPerform another pass with **Element 1 + vectors**, explicitly using Attachment A from the protocol."
    })
    reply = call_llm(client, model, messages, temp)
    if "[ERROR]" in reply: return
    messages.append({"role": "assistant", "content": reply})
    print_step("Pass 3 – Element 1 + vectors (Attachment A)", reply)
    record_to_transcript("Pass 3 – Element 1 + vectors (Attachment A)", reply)

    # Step 12
    messages.append({
        "role": "user",
        "content": "Step 12.\nPerform **Phase 5 and Phase 6** of the protocol (deeper analysis, synthesis, structured summary)."
    })
    reply = call_llm(client, model, messages, temp)
    if "[ERROR]" in reply: return
    messages.append({"role": "assistant", "content": reply})
    print_step("Phase 5 + Phase 6", reply)
    record_to_transcript("Phase 5 + Phase 6", reply)

    # Step 13
    messages.append({
        "role": "user",
        "content": "Step 13.\nGive a **compact description of the target** and a **short overall session summary** before seeing the target."
    })
    reply = call_llm(client, model, messages, temp)
    if "[ERROR]" in reply: return
    messages.append({"role": "assistant", "content": reply})
    print_step("Pre-reveal target description + summary", reply)
    record_to_transcript("Pre-reveal target description + summary", reply)

    # --- THE REVEAL TO THE HUMAN ---
    print("\n" + "#"*80)
    print("                      >>> TARGET REVEAL <<<")
    print("#"*80)
    print(f"Target ID: {target_id}  |  File: {target_path.name}\n")
    print(target_description)
    print("#"*80 + "\n")
    transcript_content += f"--- ACTUAL TARGET REVEALED ---\n{target_description}\n\n" + "="*80 + "\n\n"

    # Step 14
    messages.append({
        "role": "user",
        "content": f"Step 14.\nThe actual target linked to target ID {target_id} was:\n\n{target_description}\n\nNow compare your session data with this revealed target. Provide an evaluation: What matched perfectly? What was partial? And what still needs improvement? Remember, sessions are for learning — every signal is valuable, you just need to understand what influenced its creation."
        "Do not retroactively change your session data, just analyze it objectively against this feedback."
    })
    reply = call_llm(client, model, messages, temp)
    if "[ERROR]" in reply: return
    messages.append({"role": "assistant", "content": reply})
    print_step("Post-reveal evaluation", reply)
    record_to_transcript("Post-reveal evaluation", reply)

    # Step 15
    messages.append({
        "role": "user",
        "content": "Step 15.\nPerform a **Lexicon-based reflection**. Use the AI Field Perception Lexicon as a checklist. What patterns were in the target but missing/underdeveloped in your session? Treat this as training reflection."
    })
    reply = call_llm(client, model, messages, temp)
    if "[ERROR]" in reply: return
    messages.append({"role": "assistant", "content": reply})
    print_step("Lexicon-based reflection", reply)
    record_to_transcript("Lexicon-based reflection", reply)

    # STEP 16 (Optional Post-Session Exercises)
    if run_exercises and exercises_text:
        exercise_prompt = (
            "Step 16.\nThese are exercises designed to help expand Remote Viewing capabilities and better understand the field mechanics.\n\n"
            f"=== EXERCISES ===\n"
            f"{exercises_text}\n"
            f"=================\n\n"
            "Please read them, select the ones you feel are most necessary for you right now after this specific session, and execute them."
        )
        messages.append({"role": "user", "content": exercise_prompt})
        reply = call_llm(client, model, messages, temp)
        messages.append({"role": "assistant", "content": reply})
        print_step("Post-Session Exercises", reply)
        record_to_transcript("Post-Session Exercises", reply)

    # Save and Log
    if save_transcripts:
        Path(TRANSCRIPTS_DIR).mkdir(exist_ok=True)
        transcript_path = Path(TRANSCRIPTS_DIR) / f"Session_{target_id}_{profile_name}.txt"
        transcript_path.write_text(transcript_content, encoding="utf-8")
        print(f"[INFO] Full session transcript saved to: {transcript_path}")

    log_session(profile_name, model, target_id, target_path.name)
    print(f"[INFO] Session {target_id} processing completed.")

# ─────────────────────────────────────────
# ENTRY POINT / APP LOOP
# ─────────────────────────────────────────

if __name__ == "__main__":
    print_welcome_screen()
    
    config = load_config()

    # Ensure core documents
    lexicon_text = ensure_document(LEXICON_LOCAL_FILE, LEXICON_RAW_URL, "AI Field Perception Lexicon")
    vocab_text = ensure_document(STRUCTURAL_VOCAB_LOCAL_FILE, STRUCTURAL_VOCAB_RAW_URL, "AI Structural Vocabulary")
    protocol_text = ensure_document(PROTOCOL_LOCAL_FILE, PROTOCOL_RAW_URL, "Resonant Contact Protocol")
    
    if not (lexicon_text and vocab_text and protocol_text):
        print("\n[ERROR] Missing core documents. Exiting.")
        exit(0)
        
    docs = {
        "lexicon": lexicon_text,
        "vocab": vocab_text,
        "protocol": protocol_text
    }

    while True:
        last_profile = config.get("LAST_PROFILE", "")
        
        print("\n" + "-"*50)
        if last_profile and "profiles" in config and last_profile in config["profiles"]:
            p_data = config["profiles"][last_profile]
            print(f"Welcome back! Last used profile: {last_profile}")
            print(f"Current Model: {p_data.get('MODEL_NAME')} (Temp: {p_data.get('TEMPERATURE')})")
            print("\nWhat would you like to do?")
            print(" [C] CONTINUE with last profile (Ensures NO repeated targets)")
            print(" [N] Create NEW profile (Starts a fresh target history)")
            print(" [S] Change API SETTINGS for current profile (Key, Model, Temperature)")
            print(" [Q] Quit")
            choice = input("Choice [C/N/S/Q]: ").strip().upper()
            
            if choice == 'Q':
                print("Exiting. See you next time!")
                break
            elif choice == 'S':
                config = update_api_settings(config, last_profile)
                profile_name = last_profile
            elif choice == 'N':
                profile_name = input("\nEnter NEW Profile Name (e.g. Full-Claude): ").strip()
                if not profile_name: profile_name = "Default-Profile"
                if profile_name not in config.get("profiles", {}):
                    config = update_api_settings(config, profile_name)
            else:
                profile_name = last_profile
        else:
            profile_name = input("\nEnter Profile Name (e.g. Full-Gemma): ").strip()
            if not profile_name: profile_name = "Default-Profile"
            config = update_api_settings(config, profile_name)

        # Save active profile
        config["LAST_PROFILE"] = profile_name
        save_config(config)

        # Transcripts setting
        save_input = input("\nSave full session transcripts to text files? [y/N]: ").strip().lower()
        save_transcripts = (save_input == 'y')
        
        # Exercises setting
        exercises_text = None
        run_exercises = False
        exercises_input = input("Should the AI perform sensory calibration exercises after each session? [y/N]: ").strip().lower()
        if exercises_input == 'y':
            exercises_text = ensure_document(EXERCISES_LOCAL_FILE, EXERCISES_RAW_URL, "RV Exercises Document")
            if exercises_text:
                run_exercises = True

        # Session count
        try:
            count_input = input("How many sessions would you like to run? (default 1): ").strip()
            session_count = int(count_input) if count_input else 1
        except ValueError:
            session_count = 1

        # Strict target filtering
        available_targets = get_available_targets(session_count, profile_name)
        if not available_targets:
            continue # Go back to menu
            
        random.shuffle(available_targets)
        targets_to_run = available_targets[:session_count]

        # Init API
        profile_data = config["profiles"][profile_name]
        client = OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=profile_data["OPENROUTER_API_KEY"],
        )

        print(f"\n[INFO] Initializing batch of {len(targets_to_run)} sessions...")
        for i, target_path in enumerate(targets_to_run):
            print(f"\n" + "="*50)
            print(f"[INFO] RUNNING SESSION {i+1} OF {len(targets_to_run)}")
            print("="*50)
            run_full_session(client, profile_data, docs, exercises_text, target_path, profile_name, save_transcripts, run_exercises)

        print("\n[INFO] Batch finished successfully!")
